FROM node:alpine3.22

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY vite.config.ts ./

RUN npm install

COPY src ./src
COPY public ./public
COPY index.html .

EXPOSE 3000

CMD ["npm", "run", "dev"]