services:
  postgres:
    image: postgres:16.13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpass}
      POSTGRES_DB: ${POSTGRES_DB:-pgdb}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pguser} -d ${POSTGRES_DB:-pgdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    environment:  
      DATABASE_URL: postgresql://${DB_USERNAME:-pguser}:${DB_PASSWORD:-pgpass}@${DB_HOST:-postgres}:${DB_PORT:-5432}/${DB_NAME:-pgdb}
      RAILS_ENV: ${RAILS_ENV:-development}
      DB_HOST: ${DB_HOST:-postgres}
      DB_USERNAME: ${DB_USERNAME:-pguser}
      DB_PASSWORD: ${DB_PASSWORD:-pgpass}
      DB_NAME: ${DB_NAME:-pgdb}
      RAILS_GROUPS: ${RAILS_GROUPS:-assets}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN} # Добавь это
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}     # И это
      MANAGER_EMAIL: ${MANAGER_EMAIL}
    ports:
      - "${BACK_PORT:-8000}:3000"
    volumes:
    - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    environment: 
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/v1}
    ports:
      - "${FRONT_PORT:-3000}:80"
      
