FROM ruby:3.4.9-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    libyaml-dev \
    curl \
    net-tools \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .
RUN chmod +x ./entrypoint.sh

EXPOSE 3000

#CMD rm -f /app/tmp/pids/server.pid && \
#    exec bundle exec rails server -b 0.0.0.0 -p 3000

ENTRYPOINT ["./entrypoint.sh"] 