source "https://rubygems.org"

gem "rails", "~> 8.1.3" # rails
gem "pg", "~> 1.1" # postgresql db
gem "puma", ">= 5.0" # puma wev-server
gem "jbuilder" # build JSON API
gem "rswag", "~> 2.15"
gem "csv"
gem "jwt", "~> 2.9"
gem "bcrypt", "~> 3.1.7" # for crypt passwords
gem "rspec"



gem "image_processing", "~> 1.2" # для загрузки изображений

gem "rack-cors" # add cors
gem "rack-attack", "~> 6.7"
gem "pagy", "~> 9.3"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem "bundler-audit", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false
gem "phonelib"
  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
gem "ruby-openai"
  gem "rspec-rails", "~> 7.1"  # для rswag тестов
end
