---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/leads":
    post:
      summary: Отправить заявку на дизайн-проект (Квиз)
      tags:
      - Заявки (Leads)
      parameters: []
      responses:
        '201':
          description: Заявка успешно отправлена
        '422':
          description: Ошибка валидации (нет телефона)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                lead:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Иван
                    phone:
                      type: string
                      example: "+7 (900) 000-00-00"
                    consent:
                      type: boolean
                      example: true
                    email:
                      type: string
                      example: user@example.ru
                      nullable: true
                    comment:
                      type: string
                      example: Нужен дизайн-проект для новой квартиры
                      nullable: true
                    page_url:
                      type: string
                      example: https://site.ru/quiz
                    utm_source:
                      type: string
                      example: yandex
                      nullable: true
                    answers:
                      type: object
                      properties:
                        step_1:
                          type: string
                          example: Квартира
                        step_2:
                          type: array
                          items:
                            type: string
                          example:
                          - Кухня
                          - Гостиная
                        step_3:
                          type: integer
                          example: 85
                        step_4:
                          type: string
                          example: Минимализм
                        step_5:
                          type: string
                          example: 1 000 000 - 2 000 000 ₽
                  required:
                  - name
                  - phone
                  - consent
                  - answers
              required:
              - lead
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: smart-quiz.ru
